### ISSUE TITLE
Brainstorm

### ISSUE THREAD

**Issue by fczuardi** [CraveFood/farmblocks#1]
This is not a bug or feature request, it is only a meta issue for discussing ideas, a wishlist of things that may or may not be interesting to explore on a new project.

**Comment by fczuardi** [comment]
this project can be a good opportunity / excuse for us to review tooling and try new things as well, like, for tests, code formatting, bundling, transpiling, etc...

I have opened bug #2 for gathering feedback on our new stack and tooling for the modelsheet project.

**Comment by fczuardi** [comment]
things that are on my whishlist of fun things to try (and that can become possible with the proposed organization of treating each component as its own package) are different languages or components solutions that compile to js / react, such as [reason-react](https://github.com/reasonml/reason-react) and [nanocomponent](https://github.com/choojs/nanocomponent-adapters)

Any technology, language and stack capable of deliverying a npm-publishable react component really... [elm](https://github.com/evancz/react-elm-components)? [clojurescript](https://reagent-project.github.io/)?

**Comment by alcferreira** [comment]
closing for now...
