### ISSUE TITLE
Adjustment of color of the select component on farm blocks when disabled

### ISSUE THREAD

**Issue by LuisEduNasc** [CraveFood/farmblocks#1063]
When the select component is disabled the color of gray its off, at least on the firefox browser. See abstract components for reference: https://share.goabstract.com/16630eae-8988-4422-ac3f-eed461eae0d0?collectionLayerId=e3827e5a-dd1c-4e4f-bede-58df162760f8&mode=design

Current select disabled
![Screen Shot 2021-12-03 at 14 23 21](https://user-images.githubusercontent.com/15873582/144645867-97121f89-9731-46cc-8e94-a46199128cfe.png)
:

**Comment by alcferreira** [comment]
Fixed here: https://github.com/CraveFood/farmblocks/pull/1069
