### ISSUE TITLE
greenkeeper-lockfile breakes the lockfile

### ISSUE THREAD

**Issue by fczuardi** [CraveFood/farmblocks#114]
Similar, or the same issue as https://github.com/greenkeeperio/greenkeeper-lockfile/issues/85

After merging a greenkeeper bot PR, the new lockfile may lose the dependency range prefix, in our case greekeeper added ``"lint-staged": "^5.0.0",`` on our package.json but greenkeeper-lockfile added ``lint-staged@5.0.0:`` to the lockfile.

See https://github.com/CraveFood/farmblocks/pull/105/commits/999f57fd5aeb38d43cc59ce41eeaa417bf0f1033 and https://github.com/CraveFood/farmblocks/pull/105/commits/bfbd4b5918c84c61b6b7425ab0af392d3c401688#diff-8ee2343978836a779dc9f8d6b794c3b2R5172

The fix was to manually run ``yarn install`` again and create a new commit with:

![image](https://user-images.githubusercontent.com/7760/33020053-e5fc7db4-cde3-11e7-8a9f-dc4db7cf83a1.png)

This situation is not ideal, having to cleanup the bots work everytime defeats the purpose of having a bot.

**Comment by alcferreira** [comment]
still happening?

**Comment by fczuardi** [comment]
we workarounded the greenkeeper-lockfile bug with https://github.com/CraveFood/farmblocks/pull/163

however, greenkeeper have fixed their bug recently with https://github.com/greenkeeperio/greenkeeper-lockfile/pull/69

so we can use this issue to track our cleanup of the workaround and update of the greenkeeper-lockfile that have the proper fixed merged :)

**Comment by fczuardi** [comment]
the upstream bug is apparently fixed, we can try to remove our workaround now
