### ISSUE TITLE
property name colision causing warns on console

### ISSUE THREAD

**Issue by fczuardi** [CraveFood/farmblocks#118]
While testing stories for the Empty State I saw this on my browser's console:

![screen shot 2017-11-20 at 5 39 45 pm](https://user-images.githubusercontent.com/7760/33038312-609a6054-ce1b-11e7-8f8d-4be94c43033c.png)

This seem to be caused by how styled-components pass all props to the styled element (an html div in our case), see this comment https://github.com/styled-components/styled-components/issues/1198#issuecomment-336628848

And since the html div has a **title** property that is a string (see https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/title ) and we are forwarding a boolean value to it, react proptypes warns us about that.

This is a pretty harmless bug, but easy to solve, we could change the name of the property on the styledComponents/Text to something else.

**Comment by alcferreira** [comment]
Maybe change `title` to `isTitle` and `paragraph` to `isParagraph` (?)

**Comment by seanemmer** [comment]
I'm still experiencing this error in the latest version of styled-components.  Is it possible to use a title tag in a styled div?

**Comment by fczuardi** [comment]
Hi @seanemmer 

You can use title as a prop on a component that change the property name to something else before passing it to a styled div, example:

```jsx
import React from 'react';
import styled from 'styled-components'

const StyledDiv = styled.div`
background: ${props => props._title === "foo" ? 'yellow' : 'red'}; 
`

const MyComponent = ({ title }) => <StyledDiv _title={title}>Hello {title}!</StyledDiv>;

export default MyComponent;
```
