### ISSUE TITLE
Build task to scaffold a new component

### ISSUE THREAD

**Issue by fczuardi** [CraveFood/farmblocks#128]
The first steps in creating a new component are very similar, we could use some automation for that.
Among the tasks:

- create subdir with package.json, license and authors files
- a simple storybook story?

**Comment by fczuardi** [comment]
the lib used for promt menus by commitizen is https://github.com/sboudrias/Inquirer.js if we want to get fancy

**Comment by fczuardi** [comment]
I have named the package ``@crave/farmblocks-scaffold`` on the WIP PR, but I think that might not be a good idea, since this is a dev tool and not a farmblocks block (component).

Maybe we could use another name convention to differentiate tools from components...

``@crave/farmblocks-dev-scaffold`` might be a better package name

**Comment by fczuardi** [comment]
``@crave/farmblocks-tool-create-component``
``@crave/farmblocks-devtool-create-component``
``@crave/farmblocks-dev-init-component``...

and I still like ``@crave/farmblocks-dev-scaffold``

**Comment by alcferreira** [comment]
I like `@crave/farmblocks-dev-scaffold` (:
