### ISSUE TITLE
Helper icon gets stretched on narrow footer

### ISSUE THREAD

**Issue by fczuardi** [CraveFood/farmblocks#187]
The helper icon on the footer component should maintain it's aspect ratio when the width shrinks.

Actual result:

![screen shot 2017-12-27 at 11 17 23 am](https://user-images.githubusercontent.com/7760/34382755-3eeb668e-eaf8-11e7-91af-2971f7edcfdb.png)

**Comment by alcferreira** [comment]
![image](https://user-images.githubusercontent.com/17936244/35936288-f32e49c0-0c29-11e8-8f69-6eb7961dedb3.png)
