### ISSUE TITLE
Table header

### ISSUE THREAD

**Issue by alcferreira** [CraveFood/farmblocks#198]
https://app.zeplin.io/project/595a9cd3b401bf1876faab27/screen/59f0df64475a900a39883ff4

![image](https://user-images.githubusercontent.com/17936244/34688889-bf30a8bc-f49a-11e7-9cc1-d1790c5e945f.png)

**Comment by fczuardi** [comment]
The small dropdown menu on the last column is something that we wont be using in the near future, here is a slack chat in Portuguese:

![screen shot 2018-01-25 at 18 21 16](https://user-images.githubusercontent.com/7760/35410479-bf546be8-01fc-11e8-9816-97587b5c5e92.png)

But I added some code for custom column headers and a storybook example of how to use it anyways...
