### ISSUE TITLE
Table row

### ISSUE THREAD

**Issue by alcferreira** [CraveFood/farmblocks#199]
- [x] Medium https://app.zeplin.io/project/595a9cd3b401bf1876faab27/screen/59f0df6334f9ac1b7cb92ee4
![image](https://user-images.githubusercontent.com/17936244/34688915-dba00f2e-f49a-11e7-90b6-a18987dc429e.png)

- [x] Small https://app.zeplin.io/project/595a9cd3b401bf1876faab27/screen/59f0df63475a900a39883fc0
![image](https://user-images.githubusercontent.com/17936244/34688921-e2741fc0-f49a-11e7-8434-7ac667ebbdd8.png)

- [ ] ~~Custom~~ https://app.zeplin.io/project/595a9cd3b401bf1876faab27/screen/59f0df64a1e6b1a37f30f17b
![image](https://user-images.githubusercontent.com/17936244/34688969-0c7ddc8e-f49b-11e7-90af-3b0661615531.png)

**Comment by fczuardi** [comment]
I have opened a separated issue for the 3rd case #227
