### ISSUE TITLE
Tooling

### ISSUE THREAD

**Issue by fczuardi** [CraveFood/farmblocks#2]
One tool that I like a lot for fixing formatting/code-style/lint issues is [prettier](https://github.com/prettier/prettier), maybe we could replace eslint and the so called "standard" js with it.

I would like to experiment with [Jest](https://facebook.github.io/jest/) as well for tests, since we already have it for storyshots.

Other tool that could be part of our pipeline is a type checker, the one I like is [flow](https://flow.org/).

**Comment by fczuardi** [comment]
We could organize our commit messages and our changelog + release versions using [commitzen](https://github.com/commitizen/cz-cli) and [semantic-release](https://github.com/semantic-release/semantic-release). I have never used them in a project before, but the idea of having auto generated changelogs and not having to remember to bump the correct semver numbers sounds good...

**Comment by fczuardi** [comment]
Issue #24 is opened to track lerna publish and semantic release work

**Comment by fczuardi** [comment]
prettier, jest, flow and commitzen are running on the monorepo branch, as well as lint-staged but that one still have an issue with partial commits to be resolved (see @alcferreira comment on the pr #19 )

**Comment by alcferreira** [comment]
I'm closing this for now... We can reopen this later if necessary (:
