### ISSUE TITLE
Table header actions

### ISSUE THREAD

**Issue by alcferreira** [CraveFood/farmblocks#200]
- [x] https://app.zeplin.io/project/595a9cd3b401bf1876faab27/screen/59f0df6337c3984825ee6758
![image](https://user-images.githubusercontent.com/17936244/34689068-5ea201d4-f49b-11e7-9800-e242f43d7781.png)

**Comment by fczuardi** [comment]
example of this header actions (from invision)

![screen shot 2018-01-22 at 17 25 32](https://user-images.githubusercontent.com/7760/35240045-60d1843a-ff99-11e7-8ffb-18b8c88c054c.png)
