### ISSUE TITLE
Checkbox component

### ISSUE THREAD

**Issue by alcferreira** [CraveFood/farmblocks#203]
https://app.zeplin.io/project/595a9cd3b401bf1876faab27/screen/59ee44fef0a38ca9a6149182
https://app.zeplin.io/project/595a9cd3b401bf1876faab27/screen/59ee44fc0c2c05bfc02333f3

![image](https://user-images.githubusercontent.com/17936244/34720777-1dffff5a-f527-11e7-9733-8d714954ace4.png)

![image](https://user-images.githubusercontent.com/17936244/34723460-dcb01688-f531-11e7-9cdf-57a2e112b99e.png)

**Comment by fczuardi** [comment]
The label of the checkbox is different than the label of other input elements, as it is no uppercase and not on top of it.

**Comment by fczuardi** [comment]
this is a component that should inherit the features of validationMessages from the hoc-input, but not other features like the shadows, so for the first version I might end up exporting parts of it on the hoc-input or even duplicating code for the sake of meeting the deadline. But this is might be a good candidate for breaking the hoc-input in 2 in the future...
