### ISSUE TITLE
Integrate eslint and prettier

### ISSUE THREAD

**Issue by alcferreira** [CraveFood/farmblocks#21]
On precommit stage, integrate eslint and prettier.

https://github.com/prettier/prettier#how-does-it-compare-to-eslint-or-tslint-stylelint

**Comment by fczuardi** [comment]
👍 
What code-quality rules are important for us?

Should we select most of the ones used by the popular airbnb set? Copy the relevant ones used by the WhatsGood app?

**Comment by alcferreira** [comment]
On webapp we are using standard...

https://www.npmjs.com/package/eslint-config-standard
https://www.npmjs.com/package/eslint-config-standard-react
https://www.npmjs.com/package/eslint-plugin-standard

**Comment by fczuardi** [comment]
yeah, but the config named standard mixes both formatting and codde-quality rules, so there is potentially a lot we can remove

**Comment by alcferreira** [comment]
we can use standard but tell eslint to use prettier to check formatting rules (:

**Comment by alcferreira** [comment]
https://github.com/prettier/prettier#eslint

**Comment by fczuardi** [comment]
my point is that the conflicting rules between whatever eslint config we choose (airbnb, the one named "standard", etc) and the formatting rules from prettier, are rules that we could remove/drop from our eslint config for the sake of simplicity and faster checks...

for example, here is the output of ``npx eslint --print-config .eslintrc`` on the webapp folder:

https://gist.github.com/fczuardi/918865ff0bf331e707ec3229f86624ac

and here is the output of feeding this eslintrc file to [this CLI tool](https://github.com/prettier/eslint-config-prettier) that lists conflicting/redundant formatting rules:

```
The following rules are unnecessary or might conflict with Prettier:

- arrow-spacing
- block-spacing
- brace-style
- comma-dangle
- comma-spacing
- comma-style
- dot-location
- eol-last
- func-call-spacing
- generator-star-spacing
- indent
- jsx-quotes
- key-spacing
- keyword-spacing
- new-parens
- no-extra-parens
- no-floating-decimal
- no-mixed-spaces-and-tabs
- no-multi-spaces
- no-multiple-empty-lines
- no-trailing-spaces
- no-whitespace-before-property
- object-curly-spacing
- object-property-newline
- operator-linebreak
- padded-blocks
- react/jsx-curly-spacing
- react/jsx-equals-spacing
- react/jsx-indent
- react/jsx-space-before-closing
- rest-spread-spacing
- semi
- semi-spacing
- space-before-blocks
- space-before-function-paren
- space-in-parens
- space-infix-ops
- space-unary-ops
- standard/array-bracket-even-spacing
- standard/computed-property-even-spacing
- standard/object-curly-even-spacing
- template-curly-spacing
- template-tag-spacing
- unicode-bom
- wrap-iife
- yield-star-spacing

The following rules are enabled with options that might conflict with Prettier. See:
https://github.com/prettier/eslint-config-prettier#special-rules

- curly
- quotes

The following rules are enabled but cannot be automatically checked. See:
https://github.com/prettier/eslint-config-prettier#special-rules

- no-mixed-operators
- no-tabs
```

So there are at least 45 rules that we could kill if we go into the path of reusing eslint configs from the current eslint config that the WhatsGood webapp uses.

**Comment by fczuardi** [comment]
another visualisation of the diff: https://gist.github.com/fczuardi/c605e680e51e5bf53f72fd2edf8a3d16

**Comment by fczuardi** [comment]
regardless of the eslint rules we end up with, I suggest the eslint check to be binded in the prepush hook instead of in the precommit one (like it is the case for flow today on the monorepo branch), because the check will take longer than the reformatting of prettier alone.  And even the choice of running prettier on the precommit can be revisited later and moved to prepush if it becomes slow(not the case today).

**Comment by alcferreira** [comment]
@henlz what you think?

**Comment by fczuardi** [comment]
after answering ``eslint init`` with standard and react, then adding prettier, then react and flowtype plugins, I've ended up with this config:

```js
module.exports = {
  root: true,
  parser: "babel-eslint",
  extends: [
    "standard",
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:flowtype/recommended",
    "prettier"
  ],
  plugins: ["flowtype", "react"]
};
```

It did catch useful errors and ran fast, I am opening a PR...
