### ISSUE TITLE
Auto generate React propTypes from flow annotations

### ISSUE THREAD

**Issue by fczuardi** [CraveFood/farmblocks#22]
By using a babel plugin ([babel-plugin-flow-react-proptypes](https://github.com/brigand/babel-plugin-flow-react-proptypes)) we might be able to have both the benefits of flow typechecking and React runtime type checking without the need of duplicate definitions on our code (or annotating props arguments with a generic Object type).

The other alternative would be to use [reason-react](https://github.com/reasonml/reason-react), but that might be a bigger jump for the short term, and should be filed later as a different issue.

**Comment by alcferreira** [comment]
Also found out [babel-plugin-react-flow-props-to-prop-types](https://github.com/thejameskyle/babel-plugin-react-flow-props-to-prop-types).

**Comment by alcferreira** [comment]
@fczuardi got a bug testing this.
I opened this [issue](https://github.com/brigand/babel-plugin-flow-react-proptypes/issues/138)

**Comment by fczuardi** [comment]
For simpler comonents that dont have enum properties, just basic types like string, number, function... we could have a babel-plugin-flow-react-proptypes setup, use and follow the evolution of that project.

One of the advantages of having individual packages is the possibility to experiment different approaches within limited scopes. I tested again that plugin for the Empty State component and it generated correct propTypes.

If the plugin is harmless to other components that dont use flow then I think we could keep it on our .babelrc I am opening a new PR to add this devdependence and babel config on our project

**Comment by fczuardi** [comment]
closing as wontfix, will be dealt by #159 (we are removing flow)
