### ISSUE TITLE
fix default text input sizes

### ISSUE THREAD

**Issue by fczuardi** [CraveFood/farmblocks#224]
the total height of a regular text input should be 48px and it is current 55px:

![screen shot 2018-01-23 at 10 00 42](https://user-images.githubusercontent.com/7760/35274721-54a70870-0024-11e8-9181-b7f4e28762ab.png)
![screen shot 2018-01-23 at 09 59 50](https://user-images.githubusercontent.com/7760/35274722-54c97f22-0024-11e8-8bdf-712514ae1b00.png)

Maybe adding a box-sizing border box on the css styling fixes this...

**Comment by vNakamura** [comment]
PR #219 already fixes this as the problem was happening to search inputs too.
