### ISSUE TITLE
[Alert] Use correct style references on dismiss button

### ISSUE THREAD

**Issue by fczuardi** [CraveFood/farmblocks#23]
The spec dont clearly say what background color, color and border-shadows to use on hover and click of the dismiss button, so we used some placeholder values, this enhancement is to replace the used values with the correct ones

**Comment by fczuardi** [comment]
ok, from Slack @vitorpinho376 sent this:

![off neutral triggers small](https://user-images.githubusercontent.com/7760/30986815-1f75031a-a46b-11e7-83f4-88083c0a618a.png)

**Comment by fczuardi** [comment]
from Zeplin:

1
```
button {
  width: 32px;
  height: 32px;
  border-radius: 2.7px;
  background-color: rgba(0, 0, 0, 0.16);
  box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.16);
  border: solid 0.7px rgba(0, 0, 0, 0.16);
}
.Settings-Icon {
  width: 16px;
  height: 16px;
  background-color: rgba(255, 255, 255, 0.56);
}
```

2
```
button {
  width: 32px;
  height: 32px;
  border-radius: 2.7px;
  background-color: #3498db;
  box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.16);
  border: solid 1px rgba(0, 0, 0, 0.16);
}
.Settings-Icon {
  width: 16px;
  height: 16px;
  background-color: #ffffff;
}
```

3
```
button {
  width: 32px;
  height: 32px;
  border-radius: 2.7px;
  background-color: #3498db;
  border: solid 1px rgba(0, 0, 0, 0.16);
}
.Settings-Icon {
  width: 16px;
  height: 16px;
  background-color: #ffffff;
}
```


I am assuming 1, 2, 3 are normal, hover, click

**Comment by fczuardi** [comment]
I will implement inside the Alert component for now but I am opening an issue to extract the button as a sseparate task

**Comment by vitorpinho376** [comment]
@fczuardi The designed order is Normal, Hovered, Active and Disabled. Should i upload disabled content on Zeplin too?

**Comment by fczuardi** [comment]
no need for the disabled one, the behavior of the alert component is to not display the dismiss button if a property ```dismissable = { false }``` is set

**Comment by fczuardi** [comment]
we chose this API, instead of displaying a disabled close button because the reference for the Alert of type Refresh dont have a Icon Actionable for dismissing, and a regular button instead

**Comment by vitorpinho376** [comment]
Got it! It's better so we can share the same component. Let's break this wing, man!

**Comment by fczuardi** [comment]
ok, I have updated PR #20 we can safely close this issue now
