### ISSUE TITLE
Select box component

### ISSUE THREAD

**Issue by fczuardi** [CraveFood/farmblocks#230]
design specs:
- https://app.zeplin.io/project/595a9cd3b401bf1876faab27/screen/59ee44fec5418ce9dc2815c0

also have 2 sizes, a small for the table filters and a bigger one for the table cells:

![screen shot 2018-01-29 at 10 48 12](https://user-images.githubusercontent.com/7760/35511128-f5b5ed3c-04e1-11e8-8b3a-43692bfa806f.png)
![screen shot 2018-01-29 at 10 48 05](https://user-images.githubusercontent.com/7760/35511129-f5d6d592-04e1-11e8-9785-b6d0629e29d9.png)

https://projects.invisionapp.com/d/main#/console/13080625/273581765/preview

**Comment by alcferreira** [comment]
https://projects.invisionapp.com/d/main#/console/13207780/276092505/inspect

**Comment by fczuardi** [comment]
More references:

https://invis.io/FHFPLVJQ4YM#/276092505_---_Selects
https://invis.io/NSFPLLZEM82#/276092492_Advanced_Search_Components
