### ISSUE TITLE
Text fields with prefix and sufix

### ISSUE THREAD

**Issue by fczuardi** [CraveFood/farmblocks#234]
The text-input farmblock should be able to render fields like the ones below:

![screen shot 2018-01-31 at 15 59 39](https://user-images.githubusercontent.com/7760/35639031-02d6175c-06a0-11e8-942d-1e40bbc016c8.png)

Reference (zepling)
https://app.zeplin.io/project/595a9cd3b401bf1876faab27/screen/59ee4500c5418ce9dc281888

![screen shot 2018-01-31 at 16 11 24](https://user-images.githubusercontent.com/7760/35639454-7358d914-06a1-11e8-9e78-00b06fa34207.png)
![screen shot 2018-01-31 at 16 11 16](https://user-images.githubusercontent.com/7760/35639455-73804d0a-06a1-11e8-8914-9faedd918b96.png)

**Comment by alcferreira** [comment]
closed on https://github.com/CraveFood/farmblocks/issues/532
