### ISSUE TITLE
Form Popover

### ISSUE THREAD

**Issue by fczuardi** [CraveFood/farmblocks#248]
Implement the popover form component according to the specs available at: https://invis.io/YDFUL8AP6MQ#/276092771_Form_Popover

![screen shot 2018-02-14 at 11 38 12](https://user-images.githubusercontent.com/7760/36207007-95bdb1b6-117b-11e8-8dff-54da4e9c5298.png)

Example of current popovers that could get replaced by this new one:

![screen shot 2018-02-14 at 11 35 19](https://user-images.githubusercontent.com/7760/36206910-3d387ef4-117b-11e8-81fa-d3bbbdeee227.png)

![screen shot 2018-02-14 at 11 36 23](https://user-images.githubusercontent.com/7760/36206927-50d734be-117b-11e8-8104-dd9f9b9a95dc.png)

**Comment by fgameiro** [comment]
After the opening of this issue, we have created a new [popover component](https://cravefood.github.io/farmblocks/?selectedKind=Popover&selectedStory=Default%20-%20Link%20as%20a%20trigger&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) which accepts any content. Therefore we need to evaluate if this issue remains open or can be closed.

**Comment by fczuardi** [comment]
another form popover we need to check if it could be replaced by a form popover is the current edit inventory forms:

![image](https://user-images.githubusercontent.com/7760/43914727-0a77c756-9bdf-11e8-955b-140f372aaf3b.png)

**Comment by alcferreira** [comment]
Now we have the popover component. 
The forms are kind of unique and IMO they should be implemented on webapp side...

**Comment by fczuardi** [comment]
I think having consistency is good, to have some popovers with the cancel as a link on top-right and some with cancel button as a button on footer defeats the purpose of a design system

**Comment by alcferreira** [comment]
Actually we are going to implement a "Form wrapper". This form wrapper is gonna be a stateless component so we can use it with other components and not just with a popover.
