### ISSUE TITLE
Amount selectors 

### ISSUE THREAD

**Issue by alcferreira** [CraveFood/farmblocks#341]
https://projects.invisionapp.com/d/main#/console/13207780/276092508/preview

**Comment by fczuardi** [comment]
The update of this font on our storybook is tracked by https://github.com/CraveFood/farmblocks/issues/369

**Comment by fczuardi** [comment]
In the design specs, the increment and decrement buttons are of size 48x48 px, the existing button component dont support such size, issue #370 tracks this enhancement, but we should check with @vitorpinho376 to see if this new large size is correct or if we should be using the MEDIUM one (34px)
