### ISSUE TITLE
Icon component (with font icon)

### ISSUE THREAD

**Issue by fczuardi** [CraveFood/farmblocks#35]
Some comopnents use icons from the WhatsGood font icon.

- We should release the icon font as open source, under a Creative Commons Attribution license or something like that (investigate what font awesome and other icon fonts use and copy it)
- We should create a component for adding icons from an icon font on react projects.

**Comment by alcferreira** [comment]
Nice. We have an `Icon` component on webapp. Take a look

**Comment by vNakamura** [comment]
Closing as we moved to SVG icons and included it to farmblocks:
https://www.npmjs.com/package/@crave/farmblocks-icon
