### ISSUE TITLE
Select - duplicate check mark appearing on itens with same label

### ISSUE THREAD

**Issue by fgameiro** [CraveFood/farmblocks#355]
When a item is selected and it happens to have the same label of other item, a check mark appears in both of them, even if they are different (i.e. have different ids, or values). 

![captura de tela de 2018-05-14 21-46-17](https://user-images.githubusercontent.com/17071199/40030324-58b9d7fa-57c0-11e8-936a-bb2abec813b8.png)

**Comment by vNakamura** [comment]
I guess this can be easily fixed in the code, but if something like this situation happen in production we'll still have an UX problem.
If there's multiple options with the same label, how will the user know which one to chose?

**Comment by sbloodworth** [comment]
@vNakamura Im going to say/assume, it may only happen when we have this scenario:

AMEX ......4242
VISA...........4242

numbers will be the same, but card types different.  i think a real corner case to have multiple cards by same card type with same last 4 digits.

**Comment by vNakamura** [comment]
Yeah, you're right @sbloodworth. If someone has two cards of same flag with same las digits, they'll probably have issues in many other apps.

I'm working on this component right now for #721. I'll fix this in the same PR.
