### ISSUE TITLE
temporarily include the whatsgood iconfont on the storybook webpack of the button component

### ISSUE THREAD

**Issue by fczuardi** [CraveFood/farmblocks#38]
While the Button component don't use the Icon component (issue #35), we should improve the visuals of the button storybook by including the font family css, with the classname rule and the whatsgood iconfont files in a static folder to be served by this development local webpack server.

**Comment by alcferreira** [comment]
Why is this necessary?

**Comment by fczuardi** [comment]
not necessary for snapshots as the generated html from the stories are identical.

necessary for humans accessing the storybook to visually have the expected icons (edit, loading, meat) displayed with a font that have those icons.

**Comment by alcferreira** [comment]
Will we have to do this on any component storybook that has an icon?

**Comment by fczuardi** [comment]
hopefully not, if we end up with a good resolution for the #35 

but we arent supposed to reuse shared configs in the monorepo world, so this could be adressed by #30 as well
