### ISSUE TITLE
Investigate travis timeouts

### ISSUE THREAD

**Issue by vNakamura** [CraveFood/farmblocks#408]
This is becoming frequent, reducing our productivity.
When we push new commits, the tests would randomly become unresponsive, usually on the Storyshots tests:
![image](https://user-images.githubusercontent.com/1459283/41619777-ceff5fe6-73dd-11e8-92c6-c4fbb274de4d.png)

If we manually restart the build, the tests passes

**Comment by fczuardi** [comment]
I dont know what causes this stall, but we can try poking jest with different arguments and see if Travis like it.

On chat we discussed trying `--runInBand`, `--ci` and `--verbose`.

Lets see if they make any noticeable difference...

**Comment by fczuardi** [comment]
example of Travis build where this happened https://travis-ci.org/CraveFood/farmblocks/builds/394215182

The commit didnt change storyshots...

**Comment by fczuardi** [comment]
The freeze happen after all tests, this can be related with coveralls.js

**Comment by fczuardi** [comment]
hmm it is after tests but before the coverage table, so it might be jest and not coveralls

**Comment by fczuardi** [comment]
coveralls verbose output is way verbose, it would be nice to separate that on its own job if we find out that we need that:

https://imgur.com/Fo1apPY

**Comment by fczuardi** [comment]
travis have an option to raise this no output time: https://docs.travis-ci.com/user/common-build-problems/#my-builds-are-timing-out

we can try using this `travis_wait` with the default value (20min) and if the issue persist, we can raise that number
