### ISSUE TITLE
Create "protected" text input field

### ISSUE THREAD

**Issue by alcferreira** [CraveFood/farmblocks#426]
We need an input field that behaves like the Search Field but without the dropdown menu.

![image](https://user-images.githubusercontent.com/17936244/42292549-ae743616-7fa9-11e8-9496-3891a6233c05.png)

**Comment by fczuardi** [comment]
why not use a regular text input? what is the use case?

**Comment by fczuardi** [comment]
cc @vitorpinho376

**Comment by fczuardi** [comment]
ok, so this is for here https://projects.invisionapp.com/d/main#/console/14238554/306942225/preview

**Comment by fczuardi** [comment]
but what I am trying to understand is what this input field have that is semantically different than an input field with a value set... should we update this spec https://projects.invisionapp.com/d/main#/console/13207780/276092512/preview to cover this different input?

and what are the places / uses for it? when to use one or the other?

**Comment by fczuardi** [comment]
do users really gain something in having a field that clears all content upon clicking?

**Comment by fczuardi** [comment]
are the use cases for this type of input places where we want to start with a suggestion that have a high probability of being accepted, and discourage the editing (instead of making an invitation to editing it)? maybe that's the difference...

**Comment by alcferreira** [comment]
The goal here is to replace this component:
![2018-07-05 08 11 16](https://user-images.githubusercontent.com/17936244/42320234-07d557b8-802b-11e8-94f7-15c1f5b29a60.gif)

**Comment by vNakamura** [comment]
So the field will always have it's own submit? Never be part of a form, right?

**Comment by fczuardi** [comment]
ok, so this is like jet missile button with a cover to require an extra intention to be used

![image](https://user-images.githubusercontent.com/7760/42335090-94e1f4f2-8055-11e8-8371-dc3ca3f48271.png)

**Comment by fczuardi** [comment]
I am thinking about something along the lines of `protected` or `sealed` for the API of the component, something similar to:

```jsx
      <TextInput
        protected
        value="a protected value"
        onReplace={newValue => console.log("the entered value was:", newValue)}
        label="Field Label"
        placeholder="input value here"
      />
```

**Comment by fczuardi** [comment]
maybe this is different enough behavior to justify a new component...

**Comment by fczuardi** [comment]
or a different export on the text-tinput lib...
