### ISSUE TITLE
[Input Field] Fix focus

### ISSUE THREAD

**Issue by alcferreira** [CraveFood/farmblocks#436]
After merging https://github.com/CraveFood/farmblocks/pull/427 the input focus always goes to the end of the input even if user clicks on the middle of a work for instance.

Current behaviour
![2018-07-11 14 10 16](https://user-images.githubusercontent.com/17936244/42588555-95ee79ec-8514-11e8-84f3-17b49134d3d9.gif)

Expected behaviour
![2018-07-11 14 14 07](https://user-images.githubusercontent.com/17936244/42588608-b6305374-8514-11e8-9f79-bd96a33f776b.gif)

**Comment by fczuardi** [comment]
this is older, I think it came with the fix for #414
