### ISSUE TITLE
Add Cancel/Save buttons to Protected input

### ISSUE THREAD

**Issue by alcferreira** [CraveFood/farmblocks#438]
Reference https://projects.invisionapp.com/d/main#/console/13207780/308188844/preview

![image](https://user-images.githubusercontent.com/17936244/42594591-074f6fcc-8526-11e8-8dd9-b7773073a326.png)

**Comment by fczuardi** [comment]
this will make the reuse of the protected text field by the search field harder...

**Comment by fgameiro** [comment]
Small bug when trying to save something after saving an empty string:
![protected-input](https://user-images.githubusercontent.com/17071199/42634163-de9ac412-85b8-11e8-9249-24be579ea653.gif)

Steps:
1. edit the default value
2. save an empty string
3. edit
4. type something
5. cancel
6. edit
7. save without typing anything else (if you type, it will save)
8. it won't save
