### ISSUE TITLE
adjust increase / decrease buttons behavior for using step multiple on intermediate values

### ISSUE THREAD

**Issue by fczuardi** [CraveFood/farmblocks#465]
Currently, if the minimum or maximum caps of amount selector component are not a multiple of step, example, a minimum of 0.02 with 0.5 steps, decreasing the value with buttons to the minimum and then increasing it with the button back wont return to the previous value, example:

- value: 0.5, minimum: 0.02, step: 0.5
- click decrease, value goes to 0.02
- click increase, value goes to 0.52

As pointed in [this comment](https://github.com/CraveFood/webapp/pull/2964#issuecomment-409685745)

The same happens on the upper cap:

- value 0.5, maximum: 0.98, step: 0.5
- click increase, value goes to 0.98
- click decrease, value goes to 0.48

A more interesting behavior would be to have intermediate values that are achieved by button clicking to round to the closest multiple of the step.

**Comment by fczuardi** [comment]
`Math.round(value / step) * step`

**Comment by fczuardi** [comment]
note that this is not the same behavior as the html input type number, so if this is not worth please leave a comment and close this as invalid

**Comment by alcferreira** [comment]
Well, IMO the current behaviour is correct.

I mean, if user changes the value to `1.8` and clicks on `+` the value changes to `2.3`. It is the expected behaviour IMO. With the proposed changes, the value would be changed to `2.5`.

| Value | Click on | Current behaviour | Proposed behaviour |
|------|---------|-----------|---------|
| 1.8 | + | 2.3 | 2.5 |
| 1.8 | - | 1.3 | 1.5 |

@sbloodworth @imwra @vitorpinho376 what do you think?

**Comment by fgameiro** [comment]
We should consider where this discussion began: 

![min-amount](https://user-images.githubusercontent.com/17071199/43547167-db29e878-95b0-11e8-9520-28689a939a28.gif)

The component is working as intended and there's nothing wrong with its behavior, but IMHO it's odd  when we hit the lower bound and we get a `0.02`. Then if I hit the `+` button I get a `0.52`... I'd expect a `0.50`, which was the previous value I got, considering I did nothing to add that `0.02` to the number.

**Comment by imwra** [comment]
I think I agree with @fczuardi if I understood correctly. If you mean that we would always round to the next whole or half number (  0, 0.5, 1, 1.5, 2 etc. ), then I agree @fczuardi.

To me, as a buyer it is what makes the most sense.

**Comment by sbloodworth** [comment]
@fczuardi @fgameiro rounding is one thing the other is on input into the actual field.  0.01 whether it takes us to 0.5 or 1.0 should be allowed to be enter into the field

**Comment by fczuardi** [comment]
The text keyboard input would still allow any number in the range.

But manually entering 1.8 and then click + followed by a -, if this changes, wont take you back to 1.8. As Andre pointed. With the proposed change would make 1.8 go to 2.5 and then back to 2.0;

Today, it goes from 1.8 to 2.3 and back to 1.8 if you use buttons after typing 1.8;

But also today, the minimum possible is 0.2 so starting with 0.5 and clicking - followed by a + will make 0.5 go to 0.2 and back to 0.7. As Felipe illustrated.

So in any case we can have a increase/decrease button clicking sequence that leave you on a different number than you started, with or without the change.

I suggest leaving it as is, add a bikeshedding label and remove the card from backlog :)

**Comment by alcferreira** [comment]
I agree with @fczuardi
