### ISSUE TITLE
Revert update lerna 

### ISSUE THREAD

**Issue by alcferreira** [CraveFood/farmblocks#510]
Error to publish packages after merging https://github.com/CraveFood/farmblocks/pull/480 

```
lerna notice cli v3.1.4
lerna info versioning independent
lerna info canary enabled
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove changes before continuing.
```

**Comment by fczuardi** [comment]
It would e nice to understand what change of lerna 3 caused this,  possible starting points are:

- https://github.com/lerna/lerna/issues/1591
- https://github.com/lerna/lerna/issues/1581

I have filed #512 to properly upgrade to lerna 3 when we can

**Comment by alcferreira** [comment]
Those workarounds didn't work for us

**Comment by alcferreira** [comment]
Here are the breaking changes, but apparently none related to this bug:
https://github.com/lerna/lerna/releases/tag/v3.0.0

**Comment by fczuardi** [comment]
I left some comments on #512 with what we would need to properly migrate. For now lets just keep the working version by going forward with this revert.
