### ISSUE TITLE
Create Filter Popover component

### ISSUE THREAD

**Issue by alcferreira** [CraveFood/farmblocks#520]
![image](https://user-images.githubusercontent.com/17936244/44918766-2bc2bf80-ad12-11e8-904d-7d8882e186e9.png)

![image](https://user-images.githubusercontent.com/17936244/44918772-2f564680-ad12-11e8-91cd-ded75c8a4238.png)

![image](https://user-images.githubusercontent.com/17936244/44918778-33826400-ad12-11e8-9aca-187f57104c93.png)

**Comment by fczuardi** [comment]
those date fields are just masked text inputs, with no calendar input, is this correct?

**Comment by fczuardi** [comment]
This looks related to https://github.com/CraveFood/farmblocks/issues/248 and an opportunity to implement the form popover (a popover with a main "submit" button, a cancel on top, and some content inside).

We already have the popover component, that can be launched by a generic trigger, so we would still need to have handlers for the cancel, the submit, and a state to know if the for is filled. I will draft an api and post it here...

**Comment by fczuardi** [comment]
## Components API proposal

### FilterPopover
```jsx
<FilterPopover
    trigger={(filledStatus) => (<MyButton isFilled={filledStatus} />)}
    content={(formData) => (<MyContents data={formdata} />)}
    onSave={(newFormData) => console.dir(newFormData)}
    labels={{title: "Order Date", cancel: "Cancel", save: "Filter"}}
/>
```

### FormPopover
```jsx
<FormPopover
    titleLabel="Action Name"
    cancelLabel="Cancel"
    saveLabel="Save Changes"
    onCancel={() => console.log("form dismissed")}
    onSave={(formData) => console.dir(formData)}
    content={(formData) => (<MyContents data={formdata} />)}
/>
```

**Comment by fczuardi** [comment]
@alcferreira suggested using FormPopover as the content on FilterPopover, and @vNakamura observedvthat the content needs to have an initial formData load, so that would be something like this:

## Another Components API proposal

### FilterPopover
```jsx
<FilterPopover
    trigger={(filledStatus) => (<MyButton isFilled={filledStatus} />)}
>
    <FormPopover {...formPopoverProps} />
</FilterPopover>
```

### FormPopover
```jsx
<FormPopover
    titleLabel="Action Name"
    cancelLabel="Cancel"
    saveLabel="Save Changes"
    onCancel={() => console.log("form dismissed")}
    onSave={(formData) => console.dir(formData)}
    initialValues={myFormData}
    content={(formData) => (<MyContents data={formdata} />)}
/>
```

**Comment by fczuardi** [comment]
initial work on the FormPopover is here #531
