### ISSUE TITLE
Create Notification component on FarmBlocks (modelsheet 2.0)

### ISSUE THREAD

**Issue by henlz** [CraveFood/farmblocks#6]
From the Zeplin url:

![screen shot 2017-09-24 at 6 13 31 pm](https://user-images.githubusercontent.com/7760/30786905-30965154-a154-11e7-9659-bf78d3773068.png)

**Comment by fczuardi** [comment]
The current api for the related components on the current web app are:

**component**: Notification
- props: 
  - notification: AlertRecord

**AlertRecord**:
- type: SUCCESS_NOTIFICATION | ERROR_NOTIFICATION | WARNING_NOTIFICATION
- message: string
- icon: string
- visibleTime: number (miliseconds, default = 1500)

-----

**component**: NotificationGroupBar
- props
  - notiffications: Notification[]

-----

**component**: NotificationAnimation
- children
  - HideNotificationContainer

-----

**component**: HideNotificationContainer
- props
  - message: string
  - visibleTime: number (miliseconds, default = 1500)
- children
  - Notification[]

**Comment by fczuardi** [comment]
margins:

![screen shot 2017-09-26 at 1 11 05 pm](https://user-images.githubusercontent.com/7760/30871147-390877ae-a2bc-11e7-8fe6-740161d129a0.png)

**Comment by fczuardi** [comment]
closing as fixed as this got merged in the monorepo branch, for improvements please file new bugs
