### ISSUE TITLE
[Footer] allow other types to be passed to primary button

### ISSUE THREAD

**Issue by alcferreira** [CraveFood/farmblocks#602]
The `Footer` component has attended us just fine but now we need some more flexibility regarding the button types.

I am thinking about rewriting the footer api in order to make it more flexible.

What if we receive an array with all the "actionables" that user wants?

e.g.:

```
<Footer
  actions={[
    <Button text="Cancel" onClick={() => console.log("cancelClick")} />,
    <Button
      text="Save"
      type={buttonTypes.PRIMARY}
      onClick={() => console.log("saveClick")}
      loading={loading}
    />
  ]}
  // remaining props
/>;
  
```

Thoughts @vNakamura @fgameiro

**Comment by vNakamura** [comment]
Agreed

**Comment by fgameiro** [comment]
Agreed!
