### ISSUE TITLE
Text rendering on firefox looks bolder

### ISSUE THREAD

**Issue by alcferreira** [CraveFood/farmblocks#660]
The text component should produce the same result on every browser.

Firefox:
![image](https://user-images.githubusercontent.com/17936244/50013486-68a48080-ffa8-11e8-8708-31ac2ebeb343.png)

Chrome:
![image](https://user-images.githubusercontent.com/17936244/50013501-6e9a6180-ffa8-11e8-8a8f-29be0c466bd1.png)

Safari:
![image](https://user-images.githubusercontent.com/17936244/50013583-abfeef00-ffa8-11e8-8fcc-96da3b43f02f.png)

**Comment by alcferreira** [comment]
![image](https://user-images.githubusercontent.com/17936244/50013672-fe401000-ffa8-11e8-8b72-267d225e37a6.png)

**Comment by fgameiro** [comment]
Just a note for future reference: this bug seems to happen only in macOS High Sierra and earlier versions.
