### ISSUE TITLE
[Alert] Investigate the uses of icon on the old alert component and discuss possibly including on the farmblock

### ISSUE THREAD

**Issue by fczuardi** [CraveFood/farmblocks#69]
See https://github.com/CraveFood/webapp/issues/2246

**Comment by alcferreira** [comment]
Well I believe some time ago there used to be an icon on alert bar, but I have never seen an icon on webapp e neither the specs have have.. So I believe we don't need to worry about an icon for now

**Comment by alcferreira** [comment]
@vitorpinho376

**Comment by vitorpinho376** [comment]
Is about this we are talking about?

https://zpl.io/VQ0yoy5

**This is a new component.** A **different type** of alert 'cause it's action required. It will stick to the top, until the user closes or hit the call-to-action. This component was requested to update whatsgood versions if the users maintain their webapp open on the browser. Let me know if you have any doubts about it.
