### ISSUE TITLE
Fix inconsistency of line width among devs

### ISSUE THREAD

**Issue by vNakamura** [CraveFood/farmblocks#698]
Usually it happens on pre-commit. Prettier/ESLint will auto fix some files adding breaks in long lines or arrays. E.g. changing this:
```js
  "files": ["AUTHORS", "LICENSE", "README.md", "CHANGELOG.md", "lib"],
```
To this:
```js
  "files": [
    "AUTHORS",	
    "LICENSE",	
    "README.md",	
    "CHANGELOG.md",	
    "lib"	
  ],
```

Then later, running from another machine, it will change it back to a single line. This adds noise to the PRs.

**Comment by MateusStanki** [comment]
What you guys think about using Airbnb JS/React rules? It's a complete config solution, and cover this and other rules for us. See the style guide -> https://github.com/airbnb/javascript , and eslint package -> https://www.npmjs.com/package/eslint-config-airbnb

**Comment by vNakamura** [comment]
> What do you guys think about using Airbnb JS/React rules? It's a complete config solution, and cover this and other rules for us. See the style guide -> https://github.com/airbnb/javascript , and eslint package -> https://www.npmjs.com/package/eslint-config-airbnb

I like it. Used it in some old projects.
At the time I thought it was a bit too restrictive, but we can always customize it to our needs as we start using it

**Comment by vNakamura** [comment]
Changing the ruleset will impact the whole team, so let's get the input from everyone.
What you guys think @fgameiro and @alcferreira (when you get back).

**Comment by alcferreira** [comment]
Could be. 
But we still need to figure out why our pre-commit is behaving like that in different machines ;)

Is it due to different versions or just conflicting eslint rules?
I'm using:
node v10.7.0
pre-commit 1.10.2

**Comment by vNakamura** [comment]
node: v10.7.0
pre-commit: 1.10.5

**Comment by fgameiro** [comment]
node: v10.7.0
pre-commit: 1.10.5

**Comment by alcferreira** [comment]
Ok, let's update our pre-commit to version 1.14.2
