### ISSUE TITLE
Create CONTRIBUTION guide

### ISSUE THREAD

**Issue by henlz** [CraveFood/farmblocks#7]
Write a CONTRIBUTING guide to new developers who wish to contribute to the project.

**Comment by fczuardi** [comment]
https://help.github.com/articles/setting-guidelines-for-repository-contributors/ have 3 good examples at the bottom

**Comment by fczuardi** [comment]
closing as we have a basic one in place https://github.com/CraveFood/farmblocks/blob/master/CONTRIBUTING.md we can add a new issue to improve that later if needed
