### ISSUE TITLE
Create Multi select component

### ISSUE THREAD

**Issue by alcferreira** [CraveFood/farmblocks#721]
Specs: https://app.goabstract.com/projects/23793d20-e68f-11e8-816f-b177d180e919/branches/master/commits/fc29630f7f467aa0aae2035a2f50119faef49218/files/A1233ED6-A996-4D7E-A77E-11A55CED1624/layers/3D7225DB-4979-41AB-ACD8-676166F5E8B4?mode=build

![image](https://user-images.githubusercontent.com/17936244/54204778-bd766b00-44b3-11e9-98f3-dbcddba31cc7.png)

**Comment by vNakamura** [comment]
@alcferreira you mean this one, right?

https://share.goabstract.com/4c55bec9-a9fc-475c-8dad-4fa419090877
![image](https://user-images.githubusercontent.com/1459283/54207930-d7b34780-44b9-11e9-8d4a-acce3e035382.png)
