### ISSUE TITLE
[Modal] Set the close button to position absolute.

### ISSUE THREAD

**Issue by MateusStanki** [CraveFood/farmblocks#824]
Now, on **Modals**, our `close button` is inside a header block. That's weird because block us to add content on header without cutoff the `button` with the *showCloseIcon* prop. To fix this, we have to position it absolutely.

Also, our new farmblocks components have different `close button` style, maybe we can implement it as well. See it on **Modals**: https://share.goabstract.com/bc1e4310-5bf3-4331-8d78-ad737ad9d813?collectionLayerId=5c49410d-6aa3-44a5-a3b4-b447ac3d74af&mode=design

**Comment by alcferreira** [comment]
Needs https://github.com/CraveFood/farmblocks/pull/823
