### ISSUE TITLE
[SELECT]: Needed improvements/fixes

### ISSUE THREAD

**Issue by MateusStanki** [CraveFood/farmblocks#915]
Some component problems that need to be solved:
- [ ] Select the active item pressing `Tab` key (Currently we empty the input)
- [ ] When the `value` is `""`(empty) remove the checkmark and color style from the previously selected option (Currently the previously selected option looks like is still selected)
- [ ] Add a deselection action to the component (`x` on the end)
- [ ] Check weird spacing behavior changing the `fontsize` to display a small version of the select.
- [ ] If the selection box has scroll (e.g. passing max-height), add an opacity gradient on the end of the selection box, this will help the user identify a scroll.

**Comment by imwra** [comment]
@alcferreira, should we close this?

**Comment by alcferreira** [comment]
yeah
