### ISSUE TITLE
[Table] Increase hit area of checkboxes

### ISSUE THREAD

**Issue by alcferreira** [CraveFood/farmblocks#941]
## Current Behavior

It's common, while selecting orders, to click outside the checkbox (by mistake) and that leads to the order detail, when we go back to the listing the order selection's been lost.
![2019-08-08 17 58 19](https://user-images.githubusercontent.com/17936244/62737794-19173700-ba07-11e9-8acd-2e9457485b22.gif)

## Expected Behavior

- [ ] Expand the clickable area i.e. the whole cell containing the check box should trigger the checkbox

**Comment by imwra** [comment]
It seems like now that we removed the "card page" layout (don't know the proper term here) we should adjust the padding. Seems like the cell to the right of the checkbox has an extra 16px.

![Screen Shot 2020-04-09 at 3 20 29 AM](https://user-images.githubusercontent.com/16008216/78868553-23178c80-7a11-11ea-9851-b25028cf3dee.png)

**Comment by alcferreira** [comment]
Closing as we will have a newly designed table soon
